#!/bin/sh
#
#	Archive - Build a tarfile of things we'd want to back up.
#		  Includes mush.config, the main conf file, a flatfile,
#		  the comsys and mail databases, and text files with a
#		  .txt extension that are not help, wizhelp, or mushman.txt
#		  Symbolic links are copied, not followed. 
#
PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin:.; export PATH
#
. mush.config
#
# You'll want to use gzip if you have it. If you want really good
# compression, try 'gzip --best'. If you don't have gzip, use 'compress'.
#
ZIP=gzip
#
DBDATE=`date +%m%d-%H%M`
FLATFILE=$GAMENAME.flat.$DBDATE
#
if [ -d $BACKUP_DIR ]; then
    OUTFILE=$BACKUP_DIR/$GAMENAME-archive.$DBDATE.tar.gz
else
    OUTFILE=$GAMENAME-archive.$DBDATE.tar.gz
fi
#
#	Make a flatfile.
#
if [ -r $DATA/$GDBM_DB ]; then
    $BIN/dbconvert $DATA/$GDBM_DB x > $FLATFILE
else
    echo "No db. Backup attempt failed."
    exit 1
fi
#
#	Gather and archive.
#
TXTFILES=`ls $TEXT/*.txt | egrep -v '(help|wizhelp|mushman).txt'`
ALLFILES="$FLATFILE $DATA/comsys.db $DATA/mail.db mush.config $GAMENAME.conf $TXTFILES"
#
echo "Archiving..."
tar -chvf - $ALLFILES | $ZIP -c > $OUTFILE
rm $FLATFILE
echo "Done: $OUTFILE archive saved."
