#!/bin/sh
#
PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin:.; export PATH
LTDL_LIBRARY_PATH=./modules:./bin:.:../src:../src/modules:../src/.libs:./modules/.libs; export LTDL_LIBRARY_PATH
#
. mush.config
. check_paths
#
# You'll want to use gzip if you have it. If you want really good
# compression, try 'gzip --best'. If you don't have gzip, use 'compress'.
#
ZIP=gzip
#
DBDATE=`date +%m%d-%H%M`
#
OUTFILE=$BACKUP_DIR/$GAMENAME.$DBDATE
#
if [ -r $DATA/$GDBM_DB ]; then
    echo "Creating flatfile $OUTFILE"
    $BIN/dbconvert -c $GAMENAME.conf -x $DATA/$GDBM_DB > $OUTFILE
    echo "Creating database archive $OUTFILE.tar.gz"
    tar -cfvh - $OUTFILE $DATA/mod_*.db | $ZIP -c > $OUTFILE.tar.gz
    rm $OUTFILE
else
    echo "No dbs. Backup attempt failed."
fi
