#!/bin/sh
#
# $Id$
#
#	check_paths - Make sure mush.config paths are valid.
#		      Assumes mush.config has already been loaded in
#		      this shell.
#
if [ -z "$BIN" -o ! -d "$BIN" -o ! -r "$BIN" ]; then
	echo "Invalid BIN directory in mush.config"
	exit 1
fi
if [ -z "$TEXT" -o ! -d "$TEXT" -o ! -w "$TEXT" ]; then
	echo "Invalid TEXT directory in mush.config"
	exit 1
fi
if [ -z "$DATA" -o ! -d "$DATA" -o ! -w "$DATA" ]; then
	echo "Invalid DATA directory in mush.config"
	exit 1
fi
if [ -z "$BACKUP_DIR" -o ! -d "$BACKUP_DIR" -o ! -w "$BACKUP_DIR" ]; then
	echo "Invalid BACKUP_DIR in mush.config; using ."
	BACKUP_DIR=.
fi
