#!/bin/sh
#
# Syntax: Restore [filename]
#
PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin:.; export PATH
LTDL_LIBRARY_PATH=./modules:./bin:.:../src:../src/modules:../src/.libs:./modules/.libs; export LTDL_LIBRARY_PATH
#
. mush.config
#
ARCHIVE="$1"
#
if [ ! "$ARCHIVE" ]; then
    echo "Syntax: $0 [backup archive]"
    exit 1
fi
#
if [ ! -r $ARCHIVE ]; then
    if [ -d $BACKUP_DIR ]; then
	ARCHIVE=$BACKUP_DIR/$1
	if [ ! -r $ARCHIVE ]; then
	    echo "Error: $1 and $ARCHIVE are not valid."
	    exit 1
	fi
    else
	echo "Error: $ARCHIVE is not valid."
	exit 1
    fi
fi
#
#
# Use the flatfile extension to figure out what type of file we have to
# deal with, and how we should deal with it.
#
case $ARCHIVE in
	*.gz) UNZIP="gzip -dc"
		echo "Will use $UNZIP to uncompress gzipped archive." ;;
	*.Z) UNZIP="compress -dc"
		echo "Will use $UNZIP to uncompress compressed archive." ;;
	*) UNZIP=cat 
		echo "This archive appears to be uncompressed... okay." ;;
esac
#
# If we have other goop in the way, move it out of the way.
#
echo "Moving old files out of the way. Please ignore file-not-found warnings."
#
DBDATE=`date +%m%d-%H%M`
mkdir db-$DBDATE
mv -f $DATA/$GDBM_DB $DATA/$CRASH_DB $DATA/$BACKUP_DB $DATA/mod_*.db db-$DBDATE
#
# Reload the archive.
#
echo "Loading flatfiles."
EXT=`echo $ARCHIVE | cut -d'.' -f3`
INFILE=`echo $ARCHIVE | cut -d'.' -f1,2`
$UNZIP $ARCHIVE | tar -xf -

$BIN/dbconvert -c $GAMENAME.conf -X $DATA/$GDBM_DB < $INFILE
rm $INFILE
