#!/bin/sh

echo "Building TinyMUSH 3.1..."

echo
echo "***** Configuring GNU DBM..."
echo
cd src/gdbm-1.8.0
./configure --enable-shared=no --enable-static=yes
echo
echo "***** Building GNU DBM..."
echo
make

echo
echo "***** Configuring the server..."
cd ..
./configure
echo
echo "***** Building server using default config..."
echo
rm -f .depend
touch .depend
make 2>&1 | tee Compile.log
cd ..

echo
echo "Done."
