#!/bin/sh

echo "Building TinyMUSH 3.0..."

echo
echo "***** Configuring Sleepycat DBM..."
echo
cd src/db-3.1.17/build_unix
../dist/configure
echo
echo "***** Building Sleepycat DBM..."
echo
make

echo
echo "***** Configuring the server..."
cd ../..
./configure
echo
echo "***** Making dependencies..."
echo
make depend
echo
echo "***** Building server using default config..."
make 2>&1 | tee Compile.log
cd ..

echo
echo "Done."
